### ISSUE TITLE
Authorization format

### ISSUE THREAD

**Issue by sunwu51** [Smith-Cruise/Spring-Boot-Shiro#1]
Authorization的格式，对于JWT标准写法应该是Bearer格式吧，而我发现代码中确要求传username。
![test](https://user-images.githubusercontent.com/15844103/32643725-40877366-c618-11e7-851f-5cdd5dc22248.gif)
其他问题：
这个jwt的依赖是否能设置token的超时时间？

能否增加注解`@hasRole`的支持

**Comment by Smith-Cruise** [comment]
第一个问题：官方规范的话是使用Bearer格式，不过我之所以是要使用username是因为我要通过username来校验用户的token是否合法，这个你可以看看我的逻辑处理。其实这一块不一定要按照规范来的嘛，只要你能保证最后鉴权能成功，没有权限漏洞即可。

第二个问题：JWT的token超时时间是支持的，你看看JWT的文档吧。

第三个问题：我刚刚发现shiro官方有`shiro-spring-boot-web-starter`的整合包，有时间我会重新写下教程，到时候也能很方便的实现注解等功能。顺便那个token鉴权方式我也会重新改写的，写好了会告诉你的。

**Comment by sunwu51** [comment]
好的谢谢

**Comment by Smith-Cruise** [comment]
教程更新了，你可以看看
