### ISSUE TITLE
shiro配置注解引起重复代理的问题

### ISSUE THREAD

**Issue by zhuyaoyao2014** [Smith-Cruise/Spring-Boot-Shiro#11]

**Comment by zhuyaoyao2014** [comment]
需要改动下，强制cglib代理

/**
     * 下面的代码是添加注解支持
     */
    @Bean
    @DependsOn("lifecycleBeanPostProcessor")
    public DefaultAdvisorAutoProxyCreator defaultAdvisorAutoProxyCreator() {

        DefaultAdvisorAutoProxyCreator defaultAdvisorAutoProxyCreator = new DefaultAdvisorAutoProxyCreator();
        defaultAdvisorAutoProxyCreator.setProxyTargetClass(true);
        return defaultAdvisorAutoProxyCreator;
    }

**Comment by Smith-Cruise** [comment]
额，能讲讲为什么吗，我有点不懂

**Comment by Smith-Cruise** [comment]
不懂可以看这个 https://zhuanlan.zhihu.com/p/29161098
代码已经改写
