### ISSUE TITLE
关于Token过期如何自动延长时间或颁发新令牌?

### ISSUE THREAD

**Issue by JunX21194250** [Smith-Cruise/Spring-Boot-Shiro#14]
据我了解，JWT即使颁发新令牌也不会将旧令牌作废
不知道作者有什么思路可以分享
目前作者的DEMO 每当令牌过期后就要让用户重新登录了

**Comment by Smith-Cruise** [comment]
思路当然是有滴，就是麻烦了点。自动延长时间其实就是等于颁发新令牌，因为你延长了时间token肯定就变了。你可以在用户每次请求的时候检查令牌的时效问题，当时间即将过期的时候，返回一个状态给前端，让前端从指定接口重新拿一次令牌并替换了原来的令牌。
至于要让旧令牌失效就比较难，因为JWT并没有考虑到这个，当然你可以弄个缓存来放有效的令牌，不在缓存中则代表令牌无效。

**Comment by jiatongwu** [comment]
function send(){
    $.ajax({  
        url: "http://127.0.0.1:18080/test/save?name=ksdjf", 
        type: 'GET', 
        beforeSend: function (xhr) {  
        	xhr.setRequestHeader("Authorization", localStorage.getItem('Authorization'));
        },  
        //contentType: 'application/x-www-form-urlencoded',  
        success: function(data, textStatus, request){
        	alert(data);
        	alert(request.getResponseHeader('replace-Authorization'));
        	var s=request.getResponseHeader('replace-Authorization');
        	if(typeof(s)!="undefined"&&s!=null) {
        		localStorage.setItem('Authorization', s);	
        	} 
       }
    }); 
}

 @Override
    protected boolean executeLogin(ServletRequest request, ServletResponse response) throws Exception {
    	HttpServletResponse httpResponse=(HttpServletResponse) response;
    	HttpServletRequest httpServletRequest = (HttpServletRequest) request;
		String authorization = httpServletRequest.getHeader("Authorization");
        try {
			JWTToken token = new JWTToken(authorization);
			// 提交给realm进行登入，如果错误他会抛出异常并被捕获
			getSubject(request, response).login(token);
		} catch (Exception e) {
			throw e;
		}
        // 如果没有抛出异常则代表登入成功，返回true
        String username=JWTUtil.getUsername(authorization);
        String password=userInfoService.findByUsername(username).getPassword();
        String newToken=JWTUtil.sign(username,password);
        httpResponse.addHeader("replace-Authorization",newToken);
        return true;
    }

我是通过这种方式 来延长token的时间的，
大家 帮我看看 这样实现有什么问题吗？

**Comment by Smith-Cruise** [comment]
也是可以的
