### ISSUE TITLE
登录成功后权限访问不了

### ISSUE THREAD

**Issue by ruiluxu** [Smith-Cruise/Spring-Boot-Shiro#2]
git clone 代码，启动运行成功
1. 先访问login进行登录操作
2. 登录成功后，访问/article还是返回You are guest.
3. 登录成功后，访问/require_auth返回401.
请问下是不是还有什么需要配置的

**Comment by Smith-Cruise** [comment]
你登入成功后会获得一个token，之后请求的时候你有没有在header上面附带了这个token

**Comment by ruiluxu** [comment]
确实是的，在header上没有添加Authorization:token。非常感谢！！！

**Comment by ruiluxu** [comment]
确实是的，在header上没有添加Authorization:token。非常感谢！！！
