### ISSUE TITLE
对于401需要redirect问题有办法解决吗？

### ISSUE THREAD

**Issue by dhb52** [Smith-Cruise/Spring-Boot-Shiro#20]
否则client这边需要支持http 302 redirect才能返回正常的错误。
就算能redirect，异常的错误信息也丢失了

**Comment by Smith-Cruise** [comment]
你可以自己改写`JWTFilter`，我只是为了方便通过redirect来统一处理401，反正他都提供了`ServletRequest`和`ServletResponse`了

**Comment by dhb52** [comment]
直接使用JWTFilter.respone401
出现这个错误。java.lang.IllegalStateException: getWriter() has already been called for this response

**Comment by dhb52** [comment]
就修改了response401函数：

```
    private void response401(ServletRequest req, ServletResponse resp) {
        try {
            HttpServletResponse httpServletResponse = (HttpServletResponse) resp;
            //httpServletResponse.sendRedirect("/401");
            httpServletResponse.addHeader("ContentType", "application/json");
            PrintWriter writer = httpServletResponse.getWriter();
            writer.write("{'code': 200}");
            writer.flush();
        } catch (IOException e) {
            LOGGER.error(e.getMessage());
        }
    }
```

[stackoverflow上相关问题](https://stackoverflow.com/questions/34872170/spring-boot-replace-servletexception-response-in-filter)

**Comment by Smith-Cruise** [comment]
我也没有想出好的解决办法，不过在`getWriter()`之前使用下`reset()`方法可以正常输出，但是还是会抛出异常
