### ISSUE TITLE
如何注销呢？subject.logout（）没用

### ISSUE THREAD

**Issue by lhw1995** [Smith-Cruise/Spring-Boot-Shiro#21]

**Comment by lhw1995** [comment]
那如何手动使token过期呢？注销操作应该如何做

**Comment by Smith-Cruise** [comment]
jwt生成的token是没法手动过期的，但是可以设置过期时间。如果你一定实现手动注销功能，可以把每次生成的token放到缓存中，然后每次登入检查是否存在此缓存。
