### ISSUE TITLE
请问上传的文件是否有缺漏？

### ISSUE THREAD

**Issue by ZeroYip** [Smith-Cruise/Spring-Boot-Shiro#24]
在套用你的项目的时候，发现项目目录下不存在"Algorithm"这个文件

**Comment by Smith-Cruise** [comment]
能说的详细点吗，不都是maven自动下包吗，不需要我上传什么东西吧

**Comment by ZeroYip** [comment]
你好，我是整合到我的项目里，整合到一半才发现要导包，但是你的项目里好像不存在那个包

**Comment by ZeroYip** [comment]
请问实现login的话，URL应该怎么写？我输入"http://localhost:8080/login=smith,smith123"报404

**Comment by Smith-Cruise** [comment]
这个是post的请求啊，你这个是get方式请求
