### ISSUE TITLE
DELETE方法跨域问题

### ISSUE THREAD

**Issue by houzw** [Smith-Cruise/Spring-Boot-Shiro#26]
你好，有一个问题，`preHandle(ServletRequest request, ServletResponse response)`方法按照你的方式写好之后，执行Spring MVC 的` @DeleteMapping `的方法会报错 
Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response.
但是如果我将这一句
`httpResponse.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_METHODS, httpRequest.getMethod());`
修改为下面的样子的话，就可以正常执行
`httpResponse.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_METHODS, httpRequest.getMethod()+", DELETE");`

但我不太清楚为什么

**Comment by Smith-Cruise** [comment]
你试试`httpRequest.getMethod()`能不能取得DELETE字符串，按道理应该是可以的

**Comment by houzw** [comment]
```java
       System.out.println(httpRequest.getMethod());

        if (httpRequest.getMethod().equals(RequestMethod.OPTIONS.name())) {
            httpResponse.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, httpRequest.getHeader(HttpHeaders.ORIGIN));
            httpResponse.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_METHODS, httpRequest.getMethod()+", DELETE");
            httpResponse.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_HEADERS, httpRequest.getHeader(HttpHeaders.ACCESS_CONTROL_REQUEST_HEADERS));
            httpResponse.setStatus(HttpStatus.OK.value());
            // 该拦截器实例已处理，直接返回
            return false;
        }
```
上面这样的话是可以打印出来 DELETE 的

**Comment by Smith-Cruise** [comment]
这样我也不清楚如何解决，反正把握大体思路。OPTIONS请求时给它通过，并且设置`ALLOW_METHODS`，自己进行排查吧，我这里是没有问题的。
