### ISSUE TITLE
executeLogin执行了两次 为什么？

### ISSUE THREAD

**Issue by qumenglin** [Smith-Cruise/Spring-Boot-Shiro#29]
executeLogin执行了两次 为什么？

**Comment by Smith-Cruise** [comment]
能详细描述下情形吗

**Comment by plxh46** [comment]
我发现jwt过滤器在前就只能在方法上加注解来配置权限，否则先将其他拦截规则定制到jwt之前时就会跳到登录页面所在的地址，这种情况怎么解决啊

**Comment by plxh46** [comment]
因为在方法上加注解太过繁琐，所以我想动态权限控制，但是放到jwt过滤器前面就会跳转到登录页面所在地址。。。。

**Comment by Smith-Cruise** [comment]
额，我简书上面回了你
