### ISSUE TITLE
没跑起来

### ISSUE THREAD

**Issue by prlei** [Smith-Cruise/Spring-Boot-Shiro#3]
能看出来作者确实用心在写文档，但我能力有限跑起来有问题
hashmap怎么模拟的？
`{
  "username": "smith",
  "password": "smith123",
  "role": "user",
  "permission": "view"
}`
返回：
`{
    "code": 500,
    "msg": "Required String parameter 'username' is not present",
    "data": null
}`

**Comment by Smith-Cruise** [comment]
`{ "code": 500, "msg": "Required String parameter 'username' is not present", "data": null }`  
你返回的这个错误是SpringBoot的，因为你post请求里面不存在`username`这个字段

**Comment by prlei** [comment]
我按照您文档写的URL规则模拟的post请求，您看我的帖子
`{ "username": "smith", "password": "smith123", "role": "user", "permission": "view" }`
里面有"username": "smith“，不明白您说的 hashmap 是已经在项目里了吗？还是需要我自己去模拟？
看您文档的参数规则写的：
`
username | password | role | permission
-- | -- | -- | --
smith | smith123 | user | view
`

**Comment by Smith-Cruise** [comment]
`{ "username": "smith", "password": "smith123", "role": "user", "permission": "view" }`是我通过HashMap模拟的数据库中包含的数据，我已经模拟好了，不需要你模拟了。你只需要发送post请求，在请求中附带上`username`和`password`字段即可，你可以看我的`controller`里面已经写了`@RequestParam`，还不懂你先看看SpringBoot如何接收POST数据。

**Comment by prlei** [comment]
我没有修改任何代码，就按照您的文档跑的，如图：
[http://ww1.sinaimg.cn/large/0060lm7Tly1fnt6nsbyc8j30vs0uqtc7.jpg
](url)
参数加上 role permission 也是500错误。

**Comment by Smith-Cruise** [comment]
老哥，`username`这些字段请求不是放在body里面的，而是放在那个params里面

**Comment by prlei** [comment]
放到params确实可以了，但是朋友，前后端分离的项目一定是传json到后台啊，分离以后还传form表单，是不是有点low。

**Comment by Smith-Cruise** [comment]
你说的没错，我这边是为了简单才这样。如果要实现你的想法，要用`@RequestBody`注解。

**Comment by prlei** [comment]
明白了，sorry，也怪我没仔细读代码哈。跑起来，在顺藤摸瓜，拜读下代码。谢谢耐心解答
