### ISSUE TITLE
org.inlighting.controller.WebController#login

### ISSUE THREAD

**Issue by langlichong** [Smith-Cruise/Spring-Boot-Shiro#31]
这个方法感觉没在shiro的机制中，如果直接访问该方法映射的请求，那么整个系统就相当于进行了两次登录操作（一次是该login本身登录逻辑，一次是shiro拦截器引起的登录逻辑），感觉怪怪的，不知道你的想法是啥

**Comment by Smith-Cruise** [comment]
额，为了偷懒，没考虑这个问题

**Comment by kiwiflydream** [comment]
@Smith-Cruise  对了，还一个问题，我不太明白，那个关闭 shiro 自带 session 一定要关吗？我发现我关了之后遇到鉴权注解比如`@RequiresRoles`就会抛出未认证异常，不会主动调用doGetAuthorizationInfo方法，开启了就会调用

**Comment by Smith-Cruise** [comment]
没有你这个问题吧，我这里一切都是正常的。

**Comment by kiwiflydream** [comment]
@Smith-Cruise 谢谢回复，我改动的比较多，可能哪里影响到了，我再看看
