### ISSUE TITLE
不能注销token和删除，有什么好的解决方案吗

### ISSUE THREAD

**Issue by bzsome** [Smith-Cruise/Spring-Boot-Shiro#35]

**Comment by Smith-Cruise** [comment]
额，你可以弄个缓存，把需要注销的token放在缓存里面，每次拿到token先和需要注销的token列表里面进行比对，如果存在就注销。
当然这个方法不是很好，我觉得你可以尝试缩短token的时效，自己编写代码，当用户的token即将过期的时候，自动续期。
