### ISSUE TITLE
ShiroRealm中抛出的异常在ExceptionController中捕获到的ShiroException中其Message 被改写了

### ISSUE THREAD

**Issue by zdy1999** [Smith-Cruise/Spring-Boot-Shiro#36]
ShiroRealm中抛出的异常throw new AuthenticationException ("登录凭证已过期，请重新登录!");
在ExceptionController中捕获到的ShiroException中之前抛出的AuthenticationException其Message 被改写了

**Comment by Smith-Cruise** [comment]
被改写成了什么，或者你可以试试捕获`AuthenticationException`
