### ISSUE TITLE
fix it ?

### ISSUE THREAD

**Issue by LeeMaster** [Smith-Cruise/Spring-Boot-Shiro#39]
This subject is anonymous - it does not have any identifying principals and " +
                    "authorization operations require an identity to check against.  A Subject instance will " +
                    "acquire these identifying principals automatically after a successful login is performed " +
                    "be executing org.apache.shiro.subject.Subject.login(AuthenticationToken) or when 'Remember Me' " +
                    "functionality is enabled by the SecurityManager.  This exception can also occur when a " +
                    "previously logged-in Subject has logged out which " +
                    "makes it anonymous again.  Because an identity is currently not known due to any of these " +
                    "conditions, authorization is denied.

**Comment by Smith-Cruise** [comment]
What's mean?
