### ISSUE TITLE
验证失败

### ISSUE THREAD

**Issue by mrhym** [Smith-Cruise/Spring-Boot-Shiro#42]
使用url拼接登陆，获取token之后，获取不到权限。导致授权失败，无法访问权限页面

**Comment by mrhym** [comment]
首先已经download了你开源的代码
step 1 http://localhost:8080/login?username=danny&password=danny123 进行登陆验证
返回值：
{
    "code": 200,
    "msg": "Login success",
    "data": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NDgxMjgxODcsInVzZXJuYW1lIjoiZGFubnkifQ.2RLKFOQAiOIFGEJI4kmE_Q8Cho_hwxuPnNnspheZva4"
}
step 2 ：访问 http://localhost:8080/article 
返回值：
{
    "code": 401,
    "msg": "This subject is anonymous - it does not have any identifying principals and authorization operations require an identity to check against.  A Subject instance will acquire these identifying principals automatically after a successful login is performed be executing org.apache.shiro.subject.Subject.login(AuthenticationToken) or when 'Remember Me' functionality is enabled by the SecurityManager.  This exception can also occur when a previously logged-in Subject has logged out which makes it anonymous again.  Because an identity is currently not known due to any of these conditions, authorization is denied.",
    "data": null
}


我的问题： 登陆成功为什么授权不成功？








在 2019-01-22 11:27:47，"Smith Cruise" <notifications@github.com> 写道：


能说的详细点吗

**Comment by Smith-Cruise** [comment]
你发送的时候确定带上了token吗，注意发送的格式是`Authorization: token`，不要忘记带`Authorization`
