### ISSUE TITLE
关于doGetAuthenticationInfo的异常问题

### ISSUE THREAD

**Issue by tujietg** [Smith-Cruise/Spring-Boot-Shiro#44]
当拿token来请求的时候，存在token过期无效，token本身无效的情况，没想明白为什么要抛出User didn't existed! 和 Username or password error 的异常，两个异常是不是在登陆时抛出更好一些。

**Comment by Smith-Cruise** [comment]
请问这个异常在哪里抛出，能说详细点吗

**Comment by tujietg** [comment]
`/**
	 * 默认使用此方法进行用户名正确与否验证，错误抛出异常即可。
	 */
	@Override
	protected AuthenticationInfo doGetAuthenticationInfo(AuthenticationToken auth) throws AuthenticationException {
		String token = (String) auth.getCredentials();
		// 解密获得username，用于和数据库进行对比
		String username = JWTUtil.getUsername(token);
		if (username == null) {
			throw new AuthenticationException("token invalid");
		}

		UserBean userBean = userService.getUser(username);
		if (userBean == null) {
			throw new AuthenticationException("User didn't existed!");
		}

		if (!JWTUtil.verify(token, username, userBean.getPassword())) {
			throw new AuthenticationException("Username or password error");
		}

		return new SimpleAuthenticationInfo(token, token, "my_realm");
	}`
嗯。。我的意思，这里面的抛出的AuthenticationException的异常，个人觉得不合理。因为这个时候是含有token的验证，抛出用户不存在，用户密码不存在这样的异常个人认为不合理。

**Comment by tujietg** [comment]
抱歉，是我自己的理解出现了问题。现在搞懂了～

**Comment by Smith-Cruise** [comment]
哈哈 好吧
