### ISSUE TITLE
关于filter的两个问题请教

### ISSUE THREAD

**Issue by xiaobu1994** [Smith-Cruise/Spring-Boot-Shiro#45]
我想问下我执行的login方法JWTFilter里面的isLoginAttempt方法返回为啥为false，它的字面意思不是尝试登陆吗，
还有个executeLogin方法一直不会执行。(由于isLoginAttempt是false)我对这不是很理解。大佬指点一下

**Comment by Smith-Cruise** [comment]
额，我在哪里返回了false，代码时间有点长，忘了
