### ISSUE TITLE
@requestmapping

### ISSUE THREAD

**Issue by yaojunWang** [Smith-Cruise/Spring-Boot-Shiro#46]

**Comment by yaojunWang** [comment]
All request  return  Request method 'GET' not supported?

**Comment by Smith-Cruise** [comment]
你控制器上面是允许用GET方法的吗，而且应该是GetMapping

**Comment by yaojunWang** [comment]
除了版本，其他都拷贝的你的例子，发现启用Shiro注解后，其他的注解就有问题。

**Comment by Smith-Cruise** [comment]
也许你可以试试Spring Security来操作，个人感觉兼容性比shiro好很多:)
