### ISSUE TITLE
请问如何在Controller中获取Token中的username

### ISSUE THREAD

**Issue by huoher** [Smith-Cruise/Spring-Boot-Shiro#47]
非常感谢您的无私开源！

已反复阅读您项目的``Readme.md``内容，非常感谢。

如果用户携带token放问我，我如何在``Controller``中获取Token中的username，还是需要用户在提交时额外提交一个参数告诉我他的username呢?

**Comment by Smith-Cruise** [comment]
这个其实我在这个教程里面没有弄过，但是你可以看我的一个实际项目：
我自己使用了ThreadLocal来存放用户的username，每次请求当JWT进行解密的时候，会直接把解密后的username直接写入ThreadLocal，详情可以看 https://github.com/Eagle-OJ/eagle-oj-api/blob/master/eagle-oj-web/src/main/java/com/eagleoj/web/util/JWTUtil.java#L31

**Comment by huoher** [comment]
> 这个其实我在这个教程里面没有弄过，但是你可以看我的一个实际项目：
> 我自己使用了ThreadLocal来存放用户的username，每次请求当JWT进行解密的时候，会直接把解密后的username直接写入ThreadLocal，详情可以看 https://github.com/Eagle-OJ/eagle-oj-api/blob/master/eagle-oj-web/src/main/java/com/eagleoj/web/util/JWTUtil.java#L31

好的，非常感谢您的细心解答！
