### ISSUE TITLE
想请教个关于token安全问题

### ISSUE THREAD

**Issue by Mannggo** [Smith-Cruise/Spring-Boot-Shiro#48]
请教大佬一个问题，如果这里的secret换成一个**服务器独有的密钥**会不会好点？
因为调用者如果知道是这种签名方式，是不是能通过自己的密码来签名，然后通过设置很大的过期时间达到无限请求接口的目的？

**Comment by Smith-Cruise** [comment]
这当然可以了，密钥的规则这不是随你便嘛。确保安全不泄露就行了。

**Comment by Mannggo** [comment]
> 这当然可以了，密钥的规则这不是随你便嘛。确保安全不泄露就行了。

get！thanks
