### ISSUE TITLE
发起登录请求401

### ISSUE THREAD

**Issue by lemonade-water** [Smith-Cruise/Spring-Boot-Shiro#50]
添加了跨域，是不是要给login请求添加白名单

**Comment by Smith-Cruise** [comment]
401不是跨域的原因，你是不是把登入接口也进行安全拦截了

**Comment by lemonade-water** [comment]
不，我给login请求添加了anon

**Comment by lemonade-water** [comment]
您好，现在JWTUtil.sign()方法，com/auth0/jwt/exceptions/JWTDecodeException报错，去掉JWTUtil.sign()就不报错,原因不知道，闲时求解

**Comment by lemonade-water** [comment]
已解决！
