### ISSUE TITLE
关于filter拦截配置问题的请教

### ISSUE THREAD

**Issue by ijustlearn** [Smith-Cruise/Spring-Boot-Shiro#51]
您好：
     我想问一下，这个项目中没有使用到任何web.xml文件配置filter,也没有使用注入filter用到的FilterRegistrationBean 类，请教为什么可以做到 shiro能拦截到所有请求的，具体实现是在哪里呢，麻烦了~

**Comment by Smith-Cruise** [comment]
额，那是springboot以Bean的形式自动注入了，详情看https://github.com/Smith-Cruise/Spring-Boot-Shiro/blob/master/src/main/java/org/inlighting/shiro/ShiroConfig.java

**Comment by ijustlearn** [comment]
您好，您指的是下面的这段方法声明的Bean么，可是这个bean也没有继承 FilterRegistrationBean呢，他是如何把所有请求都拦截到shiro中的呢。

![微信截图_20190510194005](https://user-images.githubusercontent.com/17973178/57524786-785ba180-735b-11e9-8a8f-3471b501e6fb.png)


其中
filterRuleMap.put("/**", "jwt"); 这段代码我理解为在shiro拦截到请求后，再把所有的请求派发给JWTFilter吧

麻烦了，谢谢！

**Comment by ijustlearn** [comment]
![image](https://user-images.githubusercontent.com/17973178/57530619-3e45cc00-736a-11e9-8020-02a0b1cdff1a.png)
我看了一下別人的项目里面有加FilterRegistrationBean ，为啥这个项目里不需要呢，太奇怪了

**Comment by Smith-Cruise** [comment]
这个也是添加过滤器方式的一种，其实大体上是差不多的。至于整个Shiro拦截流程，我也不是很清楚，你还是打断点自己调试吧。

**Comment by ijustlearn** [comment]
![image](https://user-images.githubusercontent.com/17973178/57599150-5c891300-7588-11e9-898e-35731d281405.png)
您好：
     我今天又找了一下，原来是springboot会自动装配filter，默认映射的就是 /**  , 而 ShiroFilterFactoryBean 创建的Bean 就是一个 SpringShiroFilter 类型，总算解决心里的疑惑了， 麻烦了~
