### ISSUE TITLE
这个工具类抛出异常出错

### ISSUE THREAD

**Issue by chenweibo** [Smith-Cruise/Spring-Boot-Shiro#55]
Error:(64, 11) java: 在相应的 try 语句主体中不能抛出异常错误java.io.UnsupportedEncodingException   catch (UnsupportedEncodingException e) 生成前面这里

**Comment by Smith-Cruise** [comment]
能贴下代码吗

**Comment by chenweibo** [comment]
<img width="1588" alt="rr" src="https://user-images.githubusercontent.com/19586007/61629026-6466e100-acb6-11e9-8cb4-451dbb7bd8a6.png">
这个是IDEA的问题吗

**Comment by Smith-Cruise** [comment]
是版本问题，新版的JWT移除了这个东西，稍微改下就行了。

**Comment by chenweibo** [comment]
我修正了下 是这个I/O异常现在不能这样抛出了。
我改为
`    public static String sign(String username, String secret) {
        try {
            Date date = new Date(System.currentTimeMillis() + EXPIRE_TIME);
            Algorithm algorithm = Algorithm.HMAC256(secret);
            // 附带username信息
            return JWT.create()
                    .withClaim("username", username)
                    .withExpiresAt(date)
                    .sign(algorithm);
        } catch (Exception e) {
            return null;
        }
    }`
