### ISSUE TITLE
用户名密码验证不应该交由shiro吗？

### ISSUE THREAD

**Issue by 13129006006** [Smith-Cruise/Spring-Boot-Shiro#57]
为什么看controller是直接调用service查询用户名密码匹配的？这样也不安全吧？

**Comment by Smith-Cruise** [comment]
确实这样不合理，不过这个教程写的太老了，也没有什么时间改进。可以看我 Spring Security 的解决方案，那里解决的比较完美。

**Comment by 13129006006** [comment]
> 确实这样不合理，不过这个教程写的太老了，也没有什么时间改进。可以看我 Spring Security 的解决方案，那里解决的比较完美。

行吧，security比较难 所以打算先用shiro 哈哈
