### ISSUE TITLE
可否从token获取用户角色，或者使用缓存，减轻数据库压力。

### ISSUE THREAD

**Issue by keke122765** [Smith-Cruise/Spring-Boot-Shiro#58]
有两种方式可以得到用户角色：

1. token中得到username，验证时数据库查询此user的角色、权限信息
2. 角色、权限全部存储在token中，验证时直接从token中获取

- 缓存增强:  从缓存中读取user对应的角色、权限，若缓存内没有，则查数据库鉴权，并存入缓存。

对于大多数应用来说，角色、权限并不是经常更改的，所以我认为无须在每次请求都进行数据库查询角色权限。

将其存储在token中有如下好处：
1. 减轻正常请求的数据库压力，同时提高响应速度
2. 减少恶意请求的资源消耗(仅通过代码就可以完成请求权限判断，不会发起数据库查询，大大降低恶意请求的资源消耗，如cc攻击)

缺陷:
1. 权限更新不及时，当为用户 添加/删除 某权限后，只有重新获取token，才会真正获得权限
2. 当权限比较复杂时，token长度将大幅增加

解决方案：
  从项目要求出发，若考虑时效则前者，若考虑性能则后者，若想兼得则缓存。

**Comment by Smith-Cruise** [comment]
确实应该加入缓存，我自己的项目也有采用缓存。教程只是考虑到篇幅，就没有写。我在另一篇文章 Spring Security 中则有缓存这块的实现。
