### ISSUE TITLE
登录时未使用Shiro的认证器

### ISSUE THREAD

**Issue by mengxianglong123** [Smith-Cruise/Spring-Boot-Shiro#60]
@PostMapping("/login")
    public ResponseBean login(@RequestParam("username") String username,
                              @RequestParam("password") String password) {
        UserBean userBean = userService.getUser(username);
        if (userBean.getPassword().equals(password)) {
            return new ResponseBean(200, "Login success", JWTUtil.sign(username, password));
        } else {
            throw new UnauthorizedException();
        }
    }

这个貌似是自己验证是否登陆成功，没有使用Shiro的认证器啊，虽然这样也实现了登录功能，但是在自定义realm里面还重写了认证方法，但是最后没有去用，感觉不太合理，就是给您提个意见

**Comment by Smith-Cruise** [comment]
确实是不合理，不过因为现在我都主要用 Spring Security，而且实现的比 Shiro 更加完美。所以我就没有怎么深入 Shiro 了。🤣🤣🤣🤣🤣
