### ISSUE TITLE
JWTUtil增加refresh

### ISSUE THREAD

**Issue by lz1998** [Smith-Cruise/Spring-Boot-Shiro#61]
收到请求时刷新过期时间

**Comment by Smith-Cruise** [comment]
额，我觉得这个完全可以自己实现吧。每个人的需求可能都不一样，这里我就不加了。

**Comment by lz1998** [comment]
有没有什么推荐的做法？在每次验证时重新生成一个返回吗？感觉好像不太好

**Comment by Smith-Cruise** [comment]
token 本来就可以附带过期时间，可以每次检测他是不是即将过期。如果即将过期做出相应处理即可。
