### ISSUE TITLE
关于url拦截

### ISSUE THREAD

**Issue by WillLiaowh** [Smith-Cruise/Spring-Boot-Shiro#64]
关闭shiro自带的session，这个目的应该是为了每次请求都重新认证一次，我用post验证过，发现是因为无JSESSIONID返回，所以每次都会执行 doGetAuthenticationInfo方法认证，这是合理的。
但是我发现如果不用注解，使用url拦截的话，代码如下，又会重新返回JSESSIONID，并且只会执行一次认证，后续每次都执行doGetAuthorizationInfo方法授权
` @Bean("shiroFilter")
    public ShiroFilterFactoryBean factory(DefaultWebSecurityManager securityManager) {
        ShiroFilterFactoryBean factoryBean = new ShiroFilterFactoryBean();

        // 添加自己的过滤器并且取名为jwt
        Map<String, Filter> filterMap = new HashMap<>();
        filterMap.put("jwt", new JWTFilter());
        factoryBean.setFilters(filterMap);

        factoryBean.setSecurityManager(securityManager);
        factoryBean.setUnauthorizedUrl("/401");

        /*
         * 自定义url规则
         * http://shiro.apache.org/web.html#urls-
         */
        Map<String, String> filterRuleMap = new HashMap<>();
        filterRuleMap.put("/require_role","roles[admin]");
        // 所有请求通过我们自己的JWT Filter
        filterRuleMap.put("/**", "jwt");
        // 访问401和404页面不通过我们的Filter
        filterRuleMap.put("/401", "anon");
        factoryBean.setFilterChainDefinitionMap(filterRuleMap);
        return factoryBean;
    }`

**Comment by Smith-Cruise** [comment]
好吧，可能自己当初没有理解到位。代码过于久远，已经都忘了。。。 😭

**Comment by WillLiaowh** [comment]
这问题其实简单来说就是用url拦截替换注解拦截权限，realm并不是每次都走先认证再授权的流程
