### ISSUE TITLE
没有token 时怎么办

### ISSUE THREAD

**Issue by Sj327344558** [Smith-Cruise/Spring-Boot-Shiro#66]
如果第一次登录，浏览器中并没有token  怎么办

如果是 登录界面是springboot里给的   另外还有一个前端系统（没有登录） 想要请求 怎么解决呢

**Comment by Smith-Cruise** [comment]
你前端也要做好逻辑，如果没有token应该自行隐藏关键元素。然后如果不携带token访问关键元素，则返回401，进行跳转。

**Comment by Sj327344558** [comment]
单点登录的话&nbsp; &nbsp;第二个系统此时第一次过来 请求的话 此时shiro这边已经登录，此时 token 怎么获取呢 ，不然又得走一遍登录流程




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Smith Cruise"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 下午5:05
收件人:&nbsp;"Smith-Cruise/Spring-Boot-Shiro"<Spring-Boot-Shiro@noreply.github.com&gt;;
抄送:&nbsp;"宋杰"<327344558@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Smith-Cruise/Spring-Boot-Shiro] 没有token 时怎么办 (#66)





 
你前端也要做好逻辑，如果没有token应该自行隐藏关键元素。然后如果不携带token访问关键元素，则返回401，进行跳转。

**Comment by Smith-Cruise** [comment]
这个只能你自己想了，例如用个啥redis存储生成的key啥的，根据自己的具体业务想把。
