### ISSUE TITLE
数据库移植出了一点问题

### ISSUE THREAD

**Issue by liliangbin** [Smith-Cruise/Spring-Boot-Shiro#8]
#### 大佬你好，我就是在移植你那个数据，改到MySQL数据库时，出了一个很奇怪的问题
![img](http://39.106.148.46/img/2.png).这个是地方百度了也是没有找到什么解决办法。
##### 那个Authentication failed for token submission他是出在什么地方啦，大佬有什么解决的办法啊。头大撞墙

**Comment by Smith-Cruise** [comment]
能看看你UserService 第20行左右的代码吗

**Comment by liliangbin** [comment]
恩  那个在这里 
![img](http://39.106.148.46/img/3.png)

**Comment by Smith-Cruise** [comment]
这个就是空指针嘛，要么你`findname`根本没有没有拿到东西，返回了null。要么你`userDao`为空，没有注入进去，自己进行排查吧

**Comment by liliangbin** [comment]
我试试

**Comment by liliangbin** [comment]
大神，就是根据你的提示我去排查了一下  findname()那个方法，做 了几个测试应该是没有问题的，userDao哪里是可以拿到数据的。但是还是会出现null空指针的问题。
```java
: Authentication failed for token submission [com.example.demo.shiro.JWTToken@635744c8].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).

java.lang.NullPointerException: null
```
你可以帮我看一下是哪里出了问题么。
[shrio.zip](https://github.com/Smith-Cruise/Spring-Boot-Shiro/files/1702191/shrio.zip)

**Comment by Smith-Cruise** [comment]
这种问题还是靠自己吧，我也没时间( • ̀ω•́ )✧

**Comment by liliangbin** [comment]
嗯呢，感觉自己对jwt哪里还有点问题。我再看看，谢谢大佬给的思路。

**Comment by Smith-Cruise** [comment]
好吧，对不住了

**Comment by cheesekun** [comment]
@liliangbin 请问你解决了吗，我今天花了一天，跟你一样的错误。头发快没了

**Comment by liliangbin** [comment]
emmm,那个我也是不知道出在哪里问题，但是我后来就根据楼主的思路，我就自己重新写了一个过滤器，然后自己把那个jwt  和shiro结合起来。就可以了。我把我写好的那个例子发给你看看吧。  
https://github.com/liliangbin/spring-boot-jwt  //这个是最开始做的那个测试用写的是能够用的
https://github.com/OpenDiningHall/Open-Dining-Hall    //这个是根据那个测试后，然后写的一个小样例，

我的代码水平不是很高，也还没有多少时间来好好的修修一些小毛病。先看着吧。有事你再问我

**Comment by cheesekun** [comment]
@liliangbin 
我刚刚找到解决方法了。超级开心。
http://blog.csdn.net/u011961421/article/details/78803998
感谢你的回复。你可以去看看，可以解决问题。
