### ISSUE TITLE
关于使用前后分离，后端类RESTful风格改造配置Shiro的一些问题和想法

### ISSUE THREAD

**Issue by minghu6** [Smith-Cruise/Spring-Boot-Shiro#9]
关于项目本身:

１． 个人理解shiro的cache主要用在session方面，既然使用了JWT鉴权，似乎就没必要关心shiro的cache机制，至于验证鉴权以外其他方面的缓存需，完全可以直接使用 `spring-boot-starter-cache`, 结合其他cache实现来做．

２．jwt 串放在Header的Authorization字段上的时候一般开头是`Bearer`，隔一个空格后才是jwt串，这样区别于`Basic`和`Digest`

**Comment by minghu6** [comment]
关于shiro（吐槽）:

１．还是不太清楚为什么hash algorithm 中一直没有实现Bcrypt，搞得大家普遍两遍MD5或者手工加盐，那是零几年就提出的需求．现在还是依靠`jbcrypt` v0.4，来自己配置`BcryptPasswordMatcher (implements CredentialsMatcher)` 和 `BCryptPasswordServiceImpl (implements PasswordService)`

２．没有csrf filter，也是个老问题，官方的回答是这是浏览器正确处理cookie的问题．

３．看了整整好几天的Shiro，确实感觉它的整个设计就是传统的"大后端"， 前后一体，比如它可以和thymeleaf配合得很好．相反，前后分离，无状态，就很别扭，写得很难受．就比如lz这个就算改造得很可以的了，但是复杂度其实已经跟Spring Security 不相上下了，就有点儿 *We already walked too far, down to we had forgotten why embarked.* 其实后者也就是内容多一点儿，抽象层次叠得深一点儿，这种情况下其实可能更好．

**Comment by Smith-Cruise** [comment]
其实Cache这一块我自己的项目里面是使用了Ehcache来缓存的，但是我这里为了简单就没说，到时候我教程里面改改吧。
Authorization字段这块开头用`Bearer`这个以前也有人提过，但主要还是为了方便，就没改。
其实我觉得我这么折腾shiro还是不能很好的支持前后端分离，比如不能细化到请求类型（GET，POST）的过滤，注解写在类上面也没有效果。
CSRF的话，简单的做法在过滤器那边判断下`refer`应付下也行，其他更好的解决办法我也想不出。
也许`spring`安全框架还是要和自己亲戚`spring secruity`搭配才是最合适。(￣▽￣)~*

**Comment by minghu6** [comment]
还是我前面感受的，shiro适合且只适合不搞前后端分离，不搞RESTful的情况吧．

**Comment by Smith-Cruise** [comment]
我也是这么感觉滴

**Comment by minghu6** [comment]
关于JWT，感觉单个撑不起整个认证服务．

jwt本身较短的过期时间与用户较长的登录状态就是一个矛盾．
单用jwt做认证，发现基本上都是频繁刷新来维持长的登陆态，相当于重新登录．

还有就是在token里设置各种字段，什么`refresh_expired` 想要摆脱这种窘境．但是其实没有解决问题．

一圈看下来就是OAuth了，用jwt做短时间的`access_token`，基于session做长时间的`refresh_token`
session　放在cache（比如redis）里共享，总体算是一个折衷的方案吧.

**Comment by Smith-Cruise** [comment]
小项目还是jwt用用算了吧，这样至少简单
